name: tosepatu
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  fluttertoast: ^8.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
